name: Regression Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.html'
      - '*.md'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Let's try opting into use of Nodejs v24; see:
      #  https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
      # GitHub runners still causing problems with NodeJS v20; see:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      DEBIAN_FRONTEND: noninteractive
      TZ: America/Los_Angeles

      KAFKA_HOST: kafka

    services:
      kafka:
        # Docker Hub image 
        image: bitnamilegacy/kafka:3.0
        env:
          ALLOW_PLAINTEXT_LISTENER: 'yes'
          KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
          KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
        # Set health checks to wait until Kafka has started
        options: >-
          --health-cmd "kafka-broker-api-versions.sh --version"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      zookeeper:
        image: bitnamilegacy/zookeeper:3.8
        env:
          ALLOW_ANONYMOUS_LOGIN: 'yes'
        # Set health checks to wait until Zookeeper has started
        options: >-
          --health-cmd "echo mntr | nc -w 2 -q 2 localhost 2181"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        compiler:
          - gcc
        container:
          - ubuntu:22.04

    container: ${{ matrix.container }}

    steps:
      - name: Checkout ProFTPD
        uses: actions/checkout@v6
        with:
          repository: proftpd/proftpd
          path: proftpd

      - name: Checkout module source code
        uses: actions/checkout@v6
        with:
          path: proftpd/contrib/mod_kafka

      - name: Install Ubuntu packages
        run: |
          apt-get update -qq
          # for builds
          apt-get install -y gcc git make tzdata

          # for Kafka support
          apt-get install -y librdkafka-dev
          # for OpenSSL support
          apt-get install -y libssl-dev
          # for zlib support
          apt-get install -y zlib1g-dev

          # for integration/regression tests
          apt-get install -y \
            libauthen-oath-perl \
            libcompress-raw-zlib-perl \
            libdata-dumper-simple-perl \
            libdatetime-perl \
            libfile-copy-recursive-perl \
            libfile-path-tiny-perl \
            libfile-spec-native-perl \
            libmime-base32-perl \
            libnet-address-ip-local-perl \
            libnet-inet6glue-perl \
            libnet-ssh2-perl \
            libnet-ssleay-perl \
            libnet-telnet-perl \
            libposix-2008-perl \
            libtest-unit-perl \
            libtime-hr-perl \
            libwww-perl
          PERL_MM_USE_DEFAULT=1 perl -MCPAN -e "CPAN::Shell->notest('install', 'Gzip::Faster')"
          PERL_MM_USE_DEFAULT=1 perl -MCPAN -e "CPAN::Shell->notest('install', 'Kafka')"

          # for debugging
          gcc --version
          openssl version -a

      - name: Install with static modules
        # NOTE: Docker does not have good IPv6 support, hence we disable it.
        run: |
          cd proftpd
          ./configure --disable-ipv6 --with-modules=mod_tls:mod_kafka
          make
          ./proftpd -V
          make install

      - name: Run integration tests
        env:
          PROFTPD_TEST_BIN: /usr/local/sbin/proftpd
          PROFTPD_TEST_CI: github
          PROFTPD_TEST_DIR: ${{ github.workspace }}/proftpd/tests
        run: |
          cd proftpd/contrib/mod_kafka
          perl tests.pl
